---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: "${IMAGE:-rockylinux}-${TAG:-8}-kafka"
    hostname: kafka
    image: "${IMAGE:-rockylinux}:${TAG:-8}"
    pre_build_image: true
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    published_ports:
      - "0.0.0.0:2181:2181/tcp"
      - "0.0.0.0:9092:9092/tcp"
provisioner:
  name: ansible
  env:
    KAFKA_VERSION: ${KAFKA_VERSION:-3.0.0}
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint