---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: "${IMAGE:-rockylinux}-${TAG:-8}-kafka-1"
    hostname: kafka-1
    image: "${IMAGE:-rockylinux}:${TAG:-8}"
    pre_build_image: true
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    published_ports:
      - "0.0.0.0:2181:2181/tcp"
      - "0.0.0.0:9092:9092/tcp"
    networks:
      - name: kafka
  - name: "${IMAGE:-rockylinux}-${TAG:-8}-kafka-2"
    hostname: kafka-2
    image: "${IMAGE:-rockylinux}:${TAG:-8}"
    pre_build_image: true
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    published_ports:
      - "0.0.0.0:2182:2181/tcp"
      - "0.0.0.0:9093:9092/tcp"
    networks:
      - name: kafka
  - name: "${IMAGE:-rockylinux}-${TAG:-8}-kafka-3"
    hostname: kafka-3
    image: "${IMAGE:-rockylinux}:${TAG:-8}"
    pre_build_image: true
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    published_ports:
      - "0.0.0.0:2183:2181/tcp"
      - "0.0.0.0:9094:9092/tcp"
    networks:
      - name: kafka
provisioner:
  name: ansible
  env:
    KAFKA_VERSION: ${KAFKA_VERSION:-3.0.0}
  inventory:
    host_vars:
      ${IMAGE:-rockylinux}-${TAG:-8}-kafka-1:
        zookeeper_id: 1
        kafka_broker_id: 1
      ${IMAGE:-rockylinux}-${TAG:-8}-kafka-2:
        zookeeper_id: 2
        kafka_broker_id: 2
      ${IMAGE:-rockylinux}-${TAG:-8}-kafka-3:
        zookeeper_id: 3
        kafka_broker_id: 3
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint