on: push

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.8, 3.9]
        kafka-version: [2.1.0, 2.5.0, 2.7.0, 3.0.0]
        platform:
          - image: "centos"
            tag: "7"
          - image: "rockylinux"
            tag: "8"
          - image: "almalinux"
            tag: "8"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions

      - name: Run tox
        run: tox
        env:
          ANSIBLE_FORCE_COLOR: '1'
          IMAGE: ${{ matrix.platform.image }}
          TAG: ${{ matrix.platform.tag }}
          KAFKA_VERSION: ${{ matrix.kafka-version }}
